### ISSUE TITLE
Lock required dependencies

### ISSUE THREAD

**Issue by jgwerner** [edina/nbexchange#100]
The `nbexchange` package requires a list of dependencies for the package to work correctly. This request is to simply lock _all_ required dependencies (at least the top layer) to ensure package reproducibility.

**Comment by BertR** [comment]
Hi @jgwerner , thanks for your suggestion!
I'll put in a PR in the next days.

**Comment by jgwerner** [comment]
@BertR I actually started working on this PR but haven't submitted it due to the fact that I'm unable to install test dependencies with the `pip install .[test]` command.

I did start running tests but some are failing (most likely human error :-)).

But as soon as I get that to work I'll take care of this. Thanks!

**Comment by perllaghu** [comment]
Closed by PR #101
