### ISSUE TITLE
Configurable upload limit for assignments and submissions

### ISSUE THREAD

**Issue by BertR** [edina/nbexchange#71]
The POST /assignment and POST /submisssion endpoints
should have size limits that are user configurable.

**Comment by perllaghu** [comment]
user-configurable.... as in a config option across the whole service, or something settable on a per _something_ (course?) level?

As far as I can tell, the http protocol itself as no limit - but I think I may be able to do something for `tornado`

**Comment by perllaghu** [comment]
... and is this a server limit, or a code-limit?
(Do we want the server to respond with a `400: Bad Request` error, or send a `{"success": False, "note": "submission to big"}` response back to the plugin)

**Comment by BertR** [comment]
I would implement this by checking the 'Content-Length' header on the request going to the POST /sumission and POST /assignment handlers.
Should be configurable for the service (in nbexchange_config.py).
As for the response: should be a 400 error and include an error message
