### ISSUE TITLE
Pass student id in collect handler instead of parsing it from the submission path.

### ISSUE THREAD

**Issue by BertR** [edina/nbexchange#79]
On collection, we currently use a regex on the submission path to determine
the student id. This is error-prone and can be avoid by adding the student id to the collection endpoint.

**Comment by perllaghu** [comment]
Line 100 in the collections handler?
It was written that way to be clearer to read - the old search was clunky, cumbersome, and hard to read... however I'm always up for code improvements

(on the other hand.... the current solution only works if the default `nbgrader.coursedir.directory_structure` is used... but also see
https://gitlab.edina.ac.uk/naas/nbexchange/-/issues/5 )
